global BIOSIMROOT
BIOSIMROOT = pwd();
packages = {'/modeling', ...
'/analysis/mmil/matlab/timesurfer', ...
'/visualization/matlab/functions', ...
'/visualization/matlab/layouts', ...
'/analysis/mmil/matlab/master', ...
'/analysis/mmil/matlab/matext', ...
'/analysis/mmil/matlab/mmil_util', ...
'/analysis/mmil/matlab/csv', ...
'/analysis/mmil/matlab/fieldtrip-20080624_private', ...
'/analysis/mmil/matlab/eeglab_functions', ...
'/external/tallie', ...
'/external/tallie/funTA', ...
'/external/grant', ...
'/external/jsonlab', ...
'/external/circ_stats', ...
};

for p = 1:length(packages)
  addpath([BIOSIMROOT packages{p}]);
end

