function [allexist,volexist] = fs_checktouchfiles(subj,subjdir,nonlinregflag);
%function [allexist,volexist] = fs_checktouchfiles(subj,[subjdir],[nonlinregflag]);
%
% Required input:
%  subj is a string specifying the subject name
%
% Optional parameters:
%  subjdir - subjects directory (override SUBJECTS_DIR environment variable)
%    subjdir/subj should contain the freesurfer subject directory
%    {default = $SUBJECTS_DIR}
%  nonlinregflag - [0|1] only require minimal steps needed for nonlinregflag
%   {default: 0}
%
% Output:
%  allexist: returns 1 if all touchfiles exist, 0 otherwise
%  volexist: returns 1 if all volume touchfiles exist, 0 otherwise
%
% created:  12/22/06 by Don Hagler
% last mod: 03/19/09 by Don Hagler
% last mod: 05/14/09 by Don Hagler
% last mod: 06/10/09 by Don Hagler   removed cortical ribbon from essential
%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

allexist = 0;
volexist = 0;

surf_touchlist = {...
'lh.aparc.touch'...
'lh.aparc2.touch'...
'lh.aparcstats.touch'...
'lh.aparcstats2.touch'...
'lh.avgcurv.touch'...
'lh.final_surfaces.touch'...
'lh.inflate1.touch'...
'lh.inflate2.touch'...
'lh.qsphere.touch'...
'lh.smoothwm1.touch'...
'lh.smoothwm2.touch'...
'lh.sphmorph.touch'...
'lh.sphreg.contra.touch'...
'lh.sphreg.touch'...
'lh.tessellate.touch'...
'lh.topofix.touch'...
'rh.aparc.touch'...
'rh.aparc2.touch'...
'rh.aparcstats.touch'...
'rh.aparcstats2.touch'...
'rh.avgcurv.touch'...
'rh.final_surfaces.touch'...
'rh.inflate1.touch'...
'rh.inflate2.touch'...
'rh.qsphere.touch'...
'rh.smoothwm1.touch'...
'rh.smoothwm2.touch'...
'rh.sphmorph.touch'...
'rh.sphreg.contra.touch'...
'rh.sphreg.touch'...
'rh.tessellate.touch'...
'rh.topofix.touch'...
};

%'aparc2aseg.touch'...
%'lh.cortical_ribbon.touch'...
%'rh.cortical_ribbon.touch'...


vol_touchlist = {...
'ca_label.touch'...
'ca_normalize.touch'...
'ca_register.touch'...
'ca_register_inv.touch'...
'conform.touch'...
'em_register.touch'...
'inorm1.touch'...
'inorm2.touch'...
'mri_remove_neck.touch'...
'segstats.touch'...
'skull.lta.touch'...
'skull_strip.touch'...
'wmsegment.touch'...
};
%'fill.touch'...
%'nu.touch'...

nonlinreg_touchlist = {...
'conform.touch'...
'nu.touch'...
'longitudinal_morphsurfs.touch'...
'longitudinal_nonlinreg.touch'...
'longitudinal_nonlinregFlow.touch'...
'longitudinal_nonlinregROI_left_ROIs.touch'...
'longitudinal_nonlinregROI_right_ROIs.touch'...
};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% check parameters
if nargin<1, help(mfilename); return; end;

if ~exist('nonlinregflag','var') | isempty(nonlinregflag)
  nonlinregflag = 0;
end;

if ~exist('subjdir','var'), subjdir = []; end;
if isempty(subjdir)
  subjdir = getenv('SUBJECTS_DIR');
  if isempty(subjdir)
    error('SUBJECTS_DIR not defined as an environment variable');
  end;
end;

touchdir = sprintf('%s/%s/touch',subjdir,subj);
if ~exist(touchdir,'dir')
  fprintf('%s: WARNING: touch dir %s not found\n',mfilename,touchdir);
  return;
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if nonlinregflag
  flist = nonlinreg_touchlist;
  for f=1:length(flist)
    fname = [touchdir '/' flist{f}]; 
    if ~exist(fname,'file')
      return;
    end;
  end;
  volexist = 1;
  allexist = 1;
else
  flist = vol_touchlist;
  for f=1:length(flist)
    fname = [touchdir '/' flist{f}]; 
    if ~exist(fname,'file')
      return;
    end;
  end;
  volexist = 1;

  flist = surf_touchlist;
  for f=1:length(flist)
    fname = [touchdir '/' flist{f}]; 
    if ~exist(fname,'file')
      return;
    end;
  end;
  allexist = 1;
end;
