% movie making script for group average, multiple views, multiple conditions

subj = 'NC025_fmri_102807';
subjdir ='/space/emc2/1/halgdev/projects/nyuproj/subjects';
indir = '/home/halgdev/analysis/MEG_NYU/CMCVT/NC025_CMCVT_meg_041208/dSPM_Jun23_08_cluster/mghfiles';
outdir = 'movie_test';

tfirst = 153;
tlast = 345;
fthresh = 2.3;
fmid =2.5;
fslope = 1.2;
image_size = '400x200';

outstem = 'groupavg_multicond';

filelist = {...
  'dSPM_ssp4_mag_bem_ncov_all_cond21-spsm20-sm20-lh.mgh'...
  'dSPM_ssp4_mag_bem_ncov_all_cond21-spsm20-sm20-lh.mgh'...
  'dSPM_ssp4_mag_bem_ncov_all_cond21-spsm20-sm20-rh.mgh'...
  'dSPM_ssp4_mag_bem_ncov_all_cond21-spsm20-sm20-rh.mgh'...
  ...
  'dSPM_ssp4_mag_bem_ncov_all_cond26-spsm20-sm20-lh.mgh'...
  'dSPM_ssp4_mag_bem_ncov_all_cond26-spsm20-sm20-lh.mgh'...
  'dSPM_ssp4_mag_bem_ncov_all_cond26-spsm20-sm20-rh.mgh'...
  'dSPM_ssp4_mag_bem_ncov_all_cond26-spsm20-sm20-rh.mgh'...
};
            
hemilist =  {...
  'lh' 'lh' 'rh' 'rh'...
  'lh' 'lh' 'rh' 'rh'...
};

viewlist =  {...
  'lat' 'med' 'lat' 'med'...
  'lat' 'med' 'lat' 'med'...
};

labellist = {...
  'cond 21 lh lateral'     'cond 21 lh medial'     'cond 21 rh lateral'     'cond 21 rh medial'... 
  'cond 26 lh lateral'     'cond 26 lh medial'     'cond 26 rh lateral'     'cond 26 rh medial'... 
};

nrows = 2;
ncols = 4;

ts_surf2movie(...
  subj,...
  filelist,...
  'SUBJECTS_DIR',subjdir,...
  'label',labellist,...
  'hemi',hemilist,...
  'view',viewlist,...
  'indir',indir,...
  'outdir',outdir,...
  'image_size', image_size,...
  'outstem', outstem,...
  'sparsesmooth',0,...
  'postsmooth',0,...
  'fmid',fmid,...
  'fthresh',fthresh,...
  'fslope',fslope,...
  'tfirst',tfirst,...
  'tlast',tlast,...
  'nrows',nrows,'ncols',ncols,...
  'trim',1,...
  'hashnames',0, ...
  'timestamp','none'...
);


