%NVIEW_NOTCHFILTER Returns a discrete-time filter object.
%
%
% M-File generated by MATLAB(R) 7.5 and the Signal Processing Toolbox 6.8.
%
% Generated on: 05-Jan-2009 20:01:45
%
%
% Elliptic Bandstop filter designed using the ELLIP function.

function Hd = nview_notchfilter(samp_freqs)
    % All frequency values are in Hz.

    Fpass1 = 58.5;  % First Passband Frequency
    Fstop1 = 59.5;  % First Stopband Frequency
    Fstop2 = 60.5;  % Second Stopband Frequency
    Fpass2 = 61.5;  % Second Passband Frequency
    Apass1 = 0.5;   % First Passband Ripple (dB)
    Astop  = 60;    % Stopband Attenuation (dB)
    Apass2 = 1;     % Second Passband Ripple (dB)

    Fpass = [Fpass1 Fpass2];
    Apass = min(Apass1,Apass2);

    for i=1:length(samp_freqs)
        Fs = samp_freqs(i);  % Sampling Frequency
        % Calculate the order from the parameters using ELLIPORD.
        N = ellipord(Fpass/(Fs/2), [Fstop1 Fstop2]/(Fs/2), Apass, Astop);

        % Calculate the zpk values using the ELLIP function.
        [z,p,k] = ellip(N, Apass, Astop, Fpass/(Fs/2), 'stop');

        % To avoid round-off errors, do not use the transfer function.  Instead
        % get the zpk representation and convert it to second-order sections.
        [sos_var,g] = zp2sos(z, p, k);
        Hd(i)          = dfilt.df2sos(sos_var, g);
    end
end